spring.datasource.url=jdbc:mysql://mysql:3306/manga_db
spring.datasource.username=manga_user
spring.datasource.password=manga_pass

spring.jpa.hibernate.ddl-auto=create
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always