-- INSERTAR ADMINISTRADOR
INSERT INTO usuario (usuario, password, email, rol) 
VALUES ('admin', 'admin123', 'admin@manga.com', 'ADMIN');

-- INSERTAR USUARIO DE PRUEBA
INSERT INTO usuario (usuario, password, email, rol) 
VALUES ('user', 'user123', 'user@manga.com', 'USER');
-- AUTORES
INSERT INTO autor (nombre, nacionalidad, fecha_nacimiento, autobiografia) VALUES
('Eiichiro Oda', 'Japonesa', '1975-01-01', 'Nacido en Kumamoto, desde niño quiso ser mangaka y debutó en Shonen Jump. Es conocido por el ritmo narrativo, el humor y un universo de piratas construido durante décadas en One Piece.'),
('Masashi Kishimoto', 'Japonesa', '1974-11-08', 'Creció fascinado por el cine y el manga; Naruto nació de su interés por ninjas y por contar la historia de un marginado que persiste. Su estilo marcó a toda una generación de lectores.'),
('Tite Kubo', 'Japonesa', '1977-06-26', 'Autor con fuerte impronta visual: diseños de personajes reconocibles y escenarios entre el mundo humano y el espiritual. Bleach consolidó su mezcla de moda urbana, combates y folklore japonés.'),
('Hiro Mashima', 'Japonesa', '1977-06-26', 'Se formó leyendo Dragon Ball y creó historias de acción y amistad con ritmo ágil. Fairy Tail refleja su gusto por los gremios, la comedia y los arcos de torneo mágico.'),
('Hajime Isayama', 'Japonesa', '1977-06-26', 'Interesado en el miedo y la historia europea, planteó un mundo cercado por muros y gigantes. Su obra mezcla crítica social, tensión bélica y giros que redefinen la trama.'),
('Gege Akutami', 'Japonesa', '1977-06-26', 'Se dio a conocer con un shonen de maldiciones y artes marciales sobrenaturales. Destaca por reglas claras de poder, diseños inquietantes y un humor que contrasta con escenas duras.'),
('Kentaru Miura', 'Japonesa', '1977-06-26', 'Dibujante obsesivo con el detalle y el realismo fantástico; Berserk explora la supervivencia, la ambición y la crueldad en un mundo medieval oscuro. Su legado influyó en cómics y videojuegos de todo el mundo.'),
('Yoshihiro Togashi', 'Japonesa', '1977-06-26', 'Autor de Yu Yu Hakusho y Hunter x Hunter, famoso por sistemas de combate complejos y arcos largos. Su carrera combina éxitos editoriales con pausas por salud que alimentan el mito en torno a sus obras.'),
('Hiromu Arakawa', 'Japonesa', '1977-06-26', 'Criada en una granja de Hokkaido, llevó esa experiencia al realismo emocional y a metáforas sobre esfuerzo y pérdida. Fullmetal Alchemist equilibra aventura, política y preguntas éticas con trazo expresivo.'),
('Hisashi Sugiura', 'Japonesa', '1977-06-26', 'Mangaka orientado al thriller psicológico y al suspense; le interesan los juegos de ingenio entre antagonistas y la moral en gris. Su trabajo suele mezclar sobrenatural y crítica social ligera.'),
('Akira Toriyama', 'Japonesa', '1977-06-26', 'Figura clave del manga shonen: Dr. Slump y Dragon Ball definieron humor slapstick y batallas espectaculares. También influyó en diseño de personajes para videojuegos fuera del cómic.'),
('Makoto Yukimura', 'Japonesa', '1977-06-26', 'Apasionado por la historia vikinga y la violencia como motor narrativo, refinó un trazo cinematográfico. Vinland Saga indaga venganza, paz y madurez en un contexto histórico riguroso.'),
('Naoki Urasawa', 'Japonesa', '1977-06-26', 'Guionista y dibujante de thrillers adultos con estructura casi novelística. Monster y otras obras exploran identidad, memoria colectiva y el coste moral de las decisiones.'),
('Sui Ishida', 'Japonesa', '1977-06-26', 'Autor con formación en artes plásticas; Tokyo Ghoul mezcla horror urbano, dualidad identitaria y un Tokio nocturno muy gráfico. Su narrativa juega con el contraste entre humanos y monstruos.'),
('Kohei Horikawa', 'Japonesa', '1977-06-26', 'Fan declarado de superhéroes occidentales y de clásicos shonen, construyó un universo escolar donde el mérito y el sacrificio chocan con villanos ideológicos. Le gusta el diseño de quirks y escenas de equipo.'),
('Hiro Mashima ', 'Japonesa', '1977-06-26', 'Tras series de magos y aventureros, abordó la ciencia ficción con viajes interestelares y robots. Edens Zero retoma temas de amistad y destino con estética espacial y acción continua.'),
('Yuki Tabata', 'Japonesa', '1977-06-26', 'Debutó en revistas juveniles y consolidó un fantasy de gremios mágicos protagonizado por un héroe sin mana. Black Clover enfatiza constancia, rivalidad sana y batallas de gran escala.'),
('Jun Mochizuki', 'Japonesa', '1977-06-26', 'Influenciada por el cuento europeo y el misterio gótico, creó mundos con relojes, contratos y abismos simbólicos. Pandora Hearts destaca por puzles narrativos y diseño victoriano.'),
('Katsura Hoshino', 'Japonesa', '1977-06-26', 'Autora de fantasía oscura con exorcistas y armas vivientes; su trazo evolucionó hacia escenas más expresivas. D.Gray-man mezcla religión ficticia, horror y viajes por distintos países.'),
('Shinobu Ohtaka', 'Japonesa', '1977-06-26', 'Tomó inspiración en Las mil y una noches para mazmorras, política y aventuras juveniles. Magi combina humor, épica y reflexiones sobre liderazgo y esclavitud en un mundo de fantasía.');

-- MANGAS
INSERT INTO manga (titulo, descripcion, estado, autor_id, imagen_url, fecha_publicacion, total_capitulos)
VALUES 
('One Piece', 'Biografía: aventura de piratas donde Monkey D. Luffy, con poderes elásticos de una fruta del diablo, recluta tripulación y navega el Grand Line en busca del legendario One Piece para ser el Rey de los Piratas. Mezcla humor, acción épica y un mundo enormemente detallado.', 'EN_PUBLICACION', 1, 'https://cdn.myanimelist.net/images/manga/2/253146.jpg', '1997-07-22',1100),
('Naruto', 'Biografía: Naruto Uzumaki crece en la Aldea de la Hoja portando al zorro de nueve colas; de marginado pasa a formar el Equipo 7 y persigue el sueño de ser Hokage. Narra ninjas, vínculos y guerras entre aldeas en un shonen muy influyente.', 'FINALIZADO', 2, 'https://cdn.myanimelist.net/images/manga/3/249658.jpg', '1999-09-21', 600),
('Bleach', 'Biografía: Ichigo Kurosaki ve espíritus y acaba como shinigami sustituto, luchando contra hollows y desentrañando intrigas en la Sociedad de Almas. Combina combates con zanpakutō, humor adolescente y arcos de rescate memorables.', 'FINALIZADO', 3, 'https://myanimelist.net/images/manga/1/161558.jpg', '2001-08-07', 400),
('Fairy Tail', 'Biografía: Natsu Dragneel pertenece al gremio de magos Fairy Tail en Fiore; con Lucy, Happy, Gray y Erza encara misiones que ponen a prueba la amistad y el orgullo del gremio. Aventura mágica con fuerte idea de “familia”.', 'FINALIZADO', 4, 'https://www.salvat.com/34675-home_default/fairy-tail-n-22.jpg', '2006-08-07', 500),
('Attack on Titan', 'Biografía: la humanidad vive cercada por muros ante titanes devoradores; Eren, Mikasa y Armin se alistan y descubren secretos que cambian la historia del mundo. Thriller bélico y fantasía oscura con giros fuertes.', 'EN_PUBLICACION', 5, 'https://cdn.myanimelist.net/images/manga/2/37846.jpg', '2009-09-12', 800),
('Jujutsu Kaisen', 'Biografía: Yuji Itadori ingiere un dedo maldito de Sukuna y entra en la escuela de hechicería con Satoru Gojo, enfrentando maldiciones por grados. Acción, horror sobrenatural y reglas de energía maldita muy claras.', 'EN_PUBLICACION', 6, 'https://myanimelist.net/images/manga/3/210341.jpg', '2018-09-12', 300),
('Berserk', 'Biografía: Guts, el espadachín, sobrevive a guerras y pactos demoníacos en un mundo medieval brutal; su camino se cruza con Griffith y la Banda del Halcón. Obra adulta por su tono, violencia y dibujo detallado de Miura.', 'FINALIZADO', 7, 'https://myanimelist.net/images/manga/1/157897.jpg', '1989-08-07', 400),
('Hunter x Hunter', 'Biografía: Gon Freecss deja su isla para el examen Hunter y encontrar a su padre Ging; con Killua, Leorio y Kurapika descubre un universo de Nen y pruebas cada vez más peligrosas. Shonen con sistema de poder muy elaborado.', 'FINALIZADO', 8, 'https://myanimelist.net/images/manga/2/253119.jpg', '1998-01-07', 600),
('Fullmetal Alchemist', 'Biografía: Edward y Alphonse Elric pagan un terrible precio por una transmutación humana prohibida; Ed, alquimista estatal, busca la piedra filosofal para recuperar sus cuerpos. Política militar, equivalencia y acción.', 'FINALIZADO', 9, 'https://myanimelist.net/images/manga/3/243675.jpg', '2001-08-07', 400),
('Death Note', 'Biografía: Light Yagami halla un cuaderno capaz de matar a quien tenga nombre y rostro; el detective L lo persigue en un duelo de ingenio. Thriller psicológico sobre justicia, poder y manipulación.', 'FINALIZADO', 10, 'https://myanimelist.net/images/manga/1/258245.jpg', '2003-08-07', 600),
('Dragon Ball', 'Biografía: Son Goku, niño con fuerza sobrehumana, busca las Dragon Balls con Bulma y entrena con maestros como Roshi; la serie crece de aventura cómica a torneos y batallas cada vez más espectaculares.', 'FINALIZADO', 11, 'https://myanimelist.net/images/manga/1/267793.jpg', '1984-08-07', 400),
('Vinland Saga', 'Biografía: Thorfinn, hijo de Thors, crece entre vikingos y la sombra de Askeladd en la Inglaterra del siglo XI; la venganza choca con preguntas sobre paz y honor. Drama histórico con combates crudos.', 'FINALIZADO', 12, 'https://myanimelist.net/images/manga/2/188925.jpg', '2008-08-07', 500),
('Monster', 'Biografía: el neurocirujano Kenzo Tenma salva a un niño que años después reaparece como Johan en una trama que cruza la Alemania reunificada. Thriller de persecución y moral, estilo novela negra europea.', 'FINALIZADO', 13, 'https://myanimelist.net/images/manga/3/258224.jpg', '2004-08-07', 400),
('Tokyo Ghoul', 'Biografía: Ken Kaneki pasa a ser mitad ghoul tras un accidente y debe vivir entre humanos y depredadores, con Anteiku como refugio. Explora identidad, hambre y violencia en Tokio.', 'FINALIZADO', 14, 'https://myanimelist.net/images/manga/3/194456.jpg', '2011-08-07', 500),
('Boku no Hero Academia', 'Biografía: Izuku Midoriya nace sin quirk en un mundo de héroes pero hereda el One For All de All Might y entrena en la U.A. Shonen de crecimiento, villanos y torneos escolares.', 'FINALIZADO', 15, 'https://myanimelist.net/images/manga/1/209370.jpg', '2014-08-07', 656),
('Edens Zero', 'Biografía: Shiki Granbell, criado por robots en Granbell, sale al espacio con Rebecca y Happy buscando a la diosa Madre; ciencia ficción, Ether Gear y viajes entre planetas.', 'EN_PUBLICACION', 16, 'https://myanimelist.net/images/manga/3/212094.jpg', '2018-08-07', 200),
('Black Clover', 'Biografía: Asta y Yuno compiten por ser Rey Mago: Yuno es prodigio y Asta compensa sin mana con antimagia y esfuerzo. Aventura de gremios, demonios y el grimorio de trébol.', 'FINALIZADO', 17, 'https://myanimelist.net/images/manga/2/166254.jpg', '2015-08-07', 500),
('Pandora Hearts', 'Biografía: Oz Vessalius, en su mayoría de edad, cae al Abismo y pacta con la cadena Alice; Pandora y las casas nobles ocultan secretos sobre el tiempo y el mundo. Fantasía gótica victoriana con misterio.', 'FINALIZADO', 18, 'https://myanimelist.net/images/manga/2/169004.jpg', '2006-08-07', 400),
('DGray-man', 'Biografía: Allen Walker, exorcista con ojo maldito, destruye Akuma para la Orden Negra frente al Conde del Milenio. Mezcla religiosidad, horror y batallas con la Inocencia.', 'FINALIZADO', 19, 'https://myanimelist.net/images/manga/3/240470.jpg', '2004-08-07', 400),
('Magi', 'Biografía: Aladdin, mago con djinn en la flauta, conoce a Alibaba y a Morgiana y exploran mazmorras inspiradas en Las mil y una noches. Aventura política y mágica con reinos y los elegidos Magi.', 'FINALIZADO', 20, 'https://cdn.myanimelist.net/images/manga/3/282487.jpg', '2010-08-07', 400);

-- CAPITULOS: 
INSERT INTO capitulo (titulo, numero_capitulo, manga_id) VALUES 
-- Manga 1: One Piece
('Capítulo 1: Romance Dawn', 1, 1), ('Capítulo 2: El chico del sombrero de paja', 2, 1), ('Capítulo 3: Zoro el cazador de piratas', 3, 1), ('Capítulo 4: El Capitán Morgan', 4, 1), ('Capítulo 5: El Rey de los Piratas', 5, 1), ('Capítulo 6: La primera tripulación', 6, 1), ('Capítulo 7: Buggy el payaso', 7, 1), ('Capítulo 8: La chica ladrona', 8, 1), ('Capítulo 9: El demonio del mar', 9, 1), ('Capítulo 10: La promesa', 10, 1),
-- Manga 2: Naruto
('Capítulo 1: Uzumaki Naruto', 1, 2), ('Capítulo 2: Konohamaru', 2, 2), ('Capítulo 3: Sasuke Uchiha', 3, 2), ('Capítulo 4: Kakashi Hatake', 4, 2), ('Capítulo 5: El examen Genin', 5, 2), ('Capítulo 6: El Equipo 7', 6, 2), ('Capítulo 7: La primera misión', 7, 2), ('Capítulo 8: Camino a la Ola', 8, 2), ('Capítulo 9: Encuentro con Zabuza', 9, 2), ('Capítulo 10: El poder del Sharingan', 10, 2),
-- Manga 3: Bleach
('Capítulo 1: Ichigo Kurosaki', 1, 3), ('Capítulo 2: Shinigami sustituto', 2, 3), ('Capítulo 3: Rukia Kuchiki', 3, 3), ('Capítulo 4: El Hollow devorador', 4, 3), ('Capítulo 5: La Soul Society', 5, 3), ('Capítulo 6: Chad y Orihime', 6, 3), ('Capítulo 7: Uryu Ishida', 7, 3), ('Capítulo 8: Quincy vs Shinigami', 8, 3), ('Capítulo 9: El despertar de Zangetsu', 9, 3), ('Capítulo 10: Batalla en la ciudad', 10, 3),
-- Manga 4: Fairy Tail
('Capítulo 1: El Mago del Fuego', 1, 4), ('Capítulo 2: Lucy Heartfilia', 2, 4), ('Capítulo 3: La llegada a Magnolia', 3, 4), ('Capítulo 4: Happy el Exceed', 4, 4), ('Capítulo 5: Misión de rango S', 5, 4), ('Capítulo 6: Erza Scarlet', 6, 4), ('Capítulo 7: Gray Fullbuster', 7, 4), ('Capítulo 8: El gremio oscuro', 8, 4), ('Capítulo 9: Magia prohibida', 9, 4), ('Capítulo 10: Lucha en la isla', 10, 4),
-- Manga 5: Attack on Titan
('Capítulo 1: La caída de Shiganshina', 1, 5), ('Capítulo 2: El Titán Colosal', 2, 5), ('Capítulo 3: Mikasa y Armin', 3, 5), ('Capítulo 4: El Cuerpo de Exploración', 4, 5), ('Capítulo 5: Entrenamiento militar', 5, 5), ('Capítulo 6: El regreso de los Gigantes', 6, 5), ('Capítulo 7: El misterio del sótano', 7, 5), ('Capítulo 8: Levi Ackerman', 8, 5), ('Capítulo 9: La muralla rota', 9, 5), ('Capítulo 10: El despertar de Eren', 10, 5),
-- Manga 6: Jujutsu Kaisen
('Capítulo 1: El dedo de Sukuna', 1, 6), ('Capítulo 2: Academia de Hechicería', 2, 6), ('Capítulo 3: Satoru Gojo', 3, 6), ('Capítulo 4: Megumi Fushiguro', 4, 6), ('Capítulo 5: Maldición de grado especial', 5, 6), ('Capítulo 6: Expansión de Dominio', 6, 6), ('Capítulo 7: Nobara Kugisaki', 7, 6), ('Capítulo 8: El ritual maldito', 8, 6), ('Capítulo 9: Entrenamiento físico', 9, 6), ('Capítulo 10: Encuentro con Mahito', 10, 6),
-- Manga 7: Berserk
('Capítulo 1: El Guerrero Negro', 1, 7), ('Capítulo 2: Guts y Griffith', 2, 7), ('Capítulo 3: La Banda del Halcón', 3, 7), ('Capítulo 4: La Edad de Oro', 4, 7), ('Capítulo 5: Casca la comandante', 5, 7), ('Capítulo 6: El Behelit', 6, 7), ('Capítulo 7: Zodd el Inmortal', 7, 7), ('Capítulo 8: Mercenarios en guerra', 8, 7), ('Capítulo 9: El eclipse se acerca', 9, 7), ('Capítulo 10: Sangre y acero', 10, 7),
-- Manga 8: Hunter x Hunter
('Capítulo 1: Gon y la Isla Ballena', 1, 8), ('Capítulo 2: El examen Hunter', 2, 8), ('Capítulo 3: Killua Zoldyck', 3, 8), ('Capítulo 4: Leorio y Kurapika', 4, 8), ('Capítulo 5: Hisoka el mago', 5, 8), ('Capítulo 6: La fase final', 6, 8), ('Capítulo 7: Entrenamiento de Nen', 7, 8), ('Capítulo 8: La Torre del Cielo', 8, 8), ('Capítulo 9: El Clan Kurta', 9, 8), ('Capítulo 10: La búsqueda de Ging', 10, 8),
-- Manga 9: Fullmetal Alchemist
('Capítulo 1: Los hermanos Elric', 1, 9), ('Capítulo 2: El pecado original', 2, 9), ('Capítulo 3: Roy Mustang', 3, 9), ('Capítulo 4: Alquimia estatal', 4, 9), ('Capítulo 5: La Piedra Filosofal', 5, 9), ('Capítulo 6: Scar el vengador', 6, 9), ('Capítulo 7: Los Homúnculos', 7, 9), ('Capítulo 8: Central City', 8, 9), ('Capítulo 9: El portal de la verdad', 9, 9), ('Capítulo 10: Equivalencia e intercambio', 10, 9),
-- Manga 10: Death Note
('Capítulo 1: El cuaderno de la muerte', 1, 10), ('Capítulo 2: L vs Kira', 2, 10), ('Capítulo 3: Ryuk el Shinigami', 3, 10), ('Capítulo 4: El juego del gato y el ratón', 4, 10), ('Capítulo 5: Las reglas del Note', 5, 10), ('Capítulo 6: Vigilancia intensiva', 6, 10), ('Capítulo 7: Misa Amane', 7, 10), ('Capítulo 8: El segundo Kira', 8, 10), ('Capítulo 9: Jaque mate', 9, 10), ('Capítulo 10: Justicia divina', 10, 10),
-- Manga 11: Dragon Ball
('Capítulo 1: Goku y Bulma', 1, 11), ('Capítulo 2: Las esferas del dragón', 2, 11), ('Capítulo 3: Maestro Roshi', 3, 11), ('Capítulo 4: Entrenamiento Tortuga', 4, 11), ('Capítulo 5: El torneo de artes marciales', 5, 11), ('Capítulo 6: Krilin el rival', 6, 11), ('Capítulo 7: La Patrulla Roja', 7, 11), ('Capítulo 8: Torre del Maestro Karin', 8, 11), ('Capítulo 9: Piccolo Daimaku', 9, 11), ('Capítulo 10: El gran deseo', 10, 11),
-- Manga 12: Vinland Saga
('Capítulo 1: Thorfinn el hijo de Thors', 1, 12), ('Capítulo 2: El honor de un vikingo', 2, 12), ('Capítulo 3: Askeladd el astuto', 3, 12), ('Capítulo 4: La venganza fría', 4, 12), ('Capítulo 5: Guerras en Inglaterra', 5, 12), ('Capítulo 6: El Príncipe Canute', 6, 12), ('Capítulo 7: La batalla del puente', 7, 12), ('Capítulo 8: El sueño de Vinland', 8, 12), ('Capítulo 9: Invierno en el campamento', 9, 12), ('Capítulo 10: El fin de la tregua', 10, 12),
-- Manga 13: Monster
('Capítulo 1: El doctor Tenma', 1, 13), ('Capítulo 2: La vida humana', 2, 13), ('Capítulo 3: Johan el monstruo', 3, 13), ('Capítulo 4: Fugitivo en Alemania', 4, 13), ('Capítulo 5: El Kinderheim 511', 5, 13), ('Capítulo 6: Nina Fortner', 6, 13), ('Capítulo 7: El libro ilustrado', 7, 13), ('Capítulo 8: Crimen sin resolver', 8, 13), ('Capítulo 9: Sombras del pasado', 9, 13), ('Capítulo 10: La identidad real', 10, 13),
-- Manga 14: Tokyo Ghoul
('Capítulo 1: El accidente', 1, 14), ('Capítulo 2: Kaneki el híbrido', 2, 14), ('Capítulo 3: Café Anteiku', 3, 14), ('Capítulo 4: Touka Kirishima', 4, 14), ('Capítulo 5: El gourmet ghoul', 5, 14), ('Capítulo 6: Los inspectores palomas', 6, 14), ('Capítulo 7: Máscaras de batalla', 7, 14), ('Capítulo 8: Distrito 20', 8, 14), ('Capítulo 9: Tortura y cambio', 9, 14), ('Capítulo 10: El despertar del ciempiés', 10, 14),
-- Manga 15: Boku no Hero Academia
('Capítulo 1: Izuku el sin quirk', 1, 15), ('Capítulo 2: All Might el símbolo', 2, 15), ('Capítulo 3: Academia U.A.', 3, 15), ('Capítulo 4: Katsuki Bakugo', 4, 15), ('Capítulo 5: One For All', 5, 15), ('Capítulo 6: Examen de admisión', 6, 15), ('Capítulo 7: Shoto Todoroki', 7, 15), ('Capítulo 8: La liga de villanos', 8, 15), ('Capítulo 9: Plus Ultra', 9, 15), ('Capítulo 10: Entrenamiento de rescate', 10, 15),
-- Manga 16: Edens Zero
('Capítulo 1: Shiki y Rebecca', 1, 16), ('Capítulo 2: El robot Pino', 2, 16), ('Capítulo 3: Nave interestelar', 3, 16), ('Capítulo 4: Madre del cosmos', 4, 16), ('Capítulo 5: Poder Ether Gear', 5, 16), ('Capítulo 6: Planeta Granbell', 6, 16), ('Capítulo 7: Viaje espacial', 7, 16), ('Capítulo 8: El dragón mecánico', 8, 16), ('Capítulo 9: Estrellas brillantes', 9, 16), ('Capítulo 10: Destino cósmico', 10, 16),
-- Manga 17: Black Clover
('Capítulo 1: Asta el sin magia', 1, 17), ('Capítulo 2: Yuno el prodigio', 2, 17), ('Capítulo 3: El grimorio de trébol', 3, 17), ('Capítulo 4: Examen de Caballeros', 4, 17), ('Capítulo 5: Los Toros Negros', 5, 17), ('Capítulo 6: Yami Sukehiro', 6, 17), ('Capítulo 7: Primera misión real', 7, 17), ('Capítulo 8: Noelle Silva', 8, 17), ('Capítulo 9: El ojo del sol', 9, 17), ('Capítulo 10: Rey Mago', 10, 17),
-- Manga 18: Pandora Hearts
('Capítulo 1: Oz Vessalius', 1, 18), ('Capítulo 2: El abismo', 2, 18), ('Capítulo 3: Alice B-Rabbit', 3, 18), ('Capítulo 4: El reloj parado', 4, 18), ('Capítulo 5: Sharon Rainsworth', 5, 18), ('Capítulo 6: Cadenas rotas', 6, 18), ('Capítulo 7: Gil el sirviente', 7, 18), ('Capítulo 8: Recuerdos perdidos', 8, 18), ('Capítulo 9: El duque Nightray', 9, 18), ('Capítulo 10: Will of Abyss', 10, 18),
-- Manga 19: DGray-man
('Capítulo 1: Allen Walker', 1, 19), ('Capítulo 2: El ojo maldito', 2, 19), ('Capítulo 3: Akuma el arma', 3, 19), ('Capítulo 4: Orden Negra', 4, 19), ('Capítulo 5: Lenalee Lee', 5, 19), ('Capítulo 6: El Conde Milenario', 6, 19), ('Capítulo 7: Inocencia divina', 7, 19), ('Capítulo 8: Exorcistas en guerra', 8, 19), ('Capítulo 9: El arca de Noé', 9, 19), ('Capítulo 10: Buscando al maestro', 10, 19),
-- Manga 20: Magi
('Capítulo 1: Aladdin y Alibaba', 1, 20), ('Capítulo 2: El Laberinto de Amon', 2, 20), ('Capítulo 3: El Djinn del fuego', 3, 20), ('Capítulo 4: Morgiana la esclava', 4, 20), ('Capítulo 5: El Reino de Balbadd', 5, 20), ('Capítulo 6: Rukhs de luz', 6, 20), ('Capítulo 7: Judar el Magi oscuro', 7, 20), ('Capítulo 8: Los Siete Mares', 8, 20), ('Capítulo 9: Sinbad el Rey', 9, 20), ('Capítulo 10: La sabiduría de Solomon', 10, 20);